"""Rename payment_plan to subscription_plan

Revision ID: 61bd445225e7
Revises: 
Create Date: 2025-04-15 12:20:10.727215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61bd445225e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan', sa.String(length=50), nullable=True))
        batch_op.drop_column('payment_plan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_plan', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('subscription_plan')

    # ### end Alembic commands ###
