"""Add assigned_to column to support_tickets

Revision ID: add_assigned_to
Revises: 16ec32a8173b
Create Date: 2025-04-17 12:15:08.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_assigned_to'
down_revision = '16ec32a8173b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_support_tickets_assigned_to',
            'admin_users',
            ['assigned_to'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_support_tickets_assigned_to', type_='foreignkey')
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ### 