"""Add topic column to support_tickets

Revision ID: e9ac6620a77c
Revises: add_assigned_to
Create Date: 2025-04-21 16:40:59.538687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9ac6620a77c'
down_revision = 'add_assigned_to'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_attachments')
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('answer', sa.Text(), nullable=False))
        batch_op.drop_column('title')
        batch_op.drop_column('status')
        batch_op.drop_column('content')

    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=False))
        batch_op.alter_column('message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.create_foreign_key(None, 'support_tickets', ['ticket_id'], ['id'])
        batch_op.drop_column('filename')
        batch_op.drop_column('file_size')

    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('sender_id')
        batch_op.drop_column('sender_type')
        batch_op.drop_column('message')

    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        # First add the columns as nullable
        batch_op.add_column(sa.Column('topic', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))
        
        # Keep company_id nullable for now
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_constraint('support_tickets_ticket_number_key', type_='unique')
        batch_op.drop_constraint('fk_support_tickets_assigned_to', type_='foreignkey')

    # Update existing records with default values
    op.execute("UPDATE support_tickets SET topic = 'General' WHERE topic IS NULL")
    op.execute("UPDATE support_tickets SET details = COALESCE(description, 'No details provided') WHERE details IS NULL")
    
    # Now make the columns non-nullable
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.alter_column('topic', nullable=False)
        batch_op.alter_column('details', nullable=False)
        
        # Drop the old columns last
        batch_op.drop_column('description')
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('priority')
        batch_op.drop_column('category')
        batch_op.drop_column('ticket_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_support_tickets_assigned_to', 'admin_users', ['assigned_to'], ['id'])
        batch_op.create_unique_constraint('support_tickets_ticket_number_key', ['ticket_number'])
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('details')
        batch_op.drop_column('topic')

    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sender_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('is_admin')
        batch_op.drop_column('content')

    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('file_name')
        batch_op.drop_column('ticket_id')

    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('answer')
        batch_op.drop_column('question')

    op.create_table('support_attachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], name='support_attachments_ticket_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='support_attachments_pkey')
    )
    # ### end Alembic commands ###
